name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py


          # Write your CML report
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          
          # add images, --md for markdown formatting
          echo "## Data viz" >> report.md       #header
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          
          # publish report
          cml-send-comment report.md
